### ISSUE TITLE
conflict btw save & load

### ISSUE THREAD

**Issue by kch31411** [naver/claf#13]
https://github.com/naver/claf/blob/8ca92699a52e5fa711b012e4bc9a9be874337e4e/claf/learn/utils.py#L181
https://github.com/naver/claf/blob/8ca92699a52e5fa711b012e4bc9a9be874337e4e/claf/learn/utils.py#L198

bind_nsml에서
optimizer를 저장하고 불러오는 방식이 서로 다릅니다.
tuple이 아닌 형태로 저장을 해야될 것 같습니다.

**Comment by DongjunLee** [comment]
앗, 그렇네요 알려주셔서 감사합니다 :)
오류 수정하겠습니다.
