### ISSUE TITLE
The segmentation fault error occurred in prediction mode and Korean question & context.

### ISSUE THREAD

**Issue by znu808** [naver/claf#2]
Hi, 

Now I'm testing the Claf BERT with KorQuad data set. 
After trainning, I had got the checkpoint file(model_22000.pkl)

And then I had to tried predict using predict.py, but Segmentation Fault error occured like below log.
(However, in English case, it's normally executed) 

So could you advise how to fix this error ?

**# English case (Okay)**
/home/pycharm/.conda/envs/claf/bin/python -u /home/pycharm/workspace/claf_test/predict.py logs/squad_bert/checkpoint/model_22000.pkl --cuda_devices 0 --question test --context test
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
**Predict: {'text': 'test', 'score': -0.8118173778057098}**

Process finished with exit code 0

**# Korean case (Segmentation Fault)**
/home/pycharm/.conda/envs/claf/bin/python -u /home/pycharm/workspace/claf_test/predict.py logs/squad_bert/checkpoint/model_22000.pkl --cuda_devices 0 --question 한글 --context 한글
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
**bash: line 1: 174065 Segmentation fault      (core dumped) env "PYTHONUNBUFFERED"="1" "PYTHONPATH"="/home/pycharm/workspace/2944/claf_test:/home/pycharm/.pycharm_helpers/pycharm_matplotlib_backend" "PYCHARM_HOSTED"="1" "JETBRAINS_REMOTE_RUN"="1" "PYCHARM_MATPLOTLIB_PORT"="64594" "PYTHONIOENCODING"="UTF-8" '/home/pycharm/.conda/envs/claf/bin/python' '-u' '/home/pycharm/workspace/2944/claf_test/predict.py' 'logs/squad_bert/checkpoint/model_22000.pkl' '--cuda_devices' '0' '--question' '한글' '--context' '한글'**

**Comment by DongjunLee** [comment]
Hi, Thanks for issuing.

First of all, I think encoding is the problem because English has worked but, not Korean.
However, I am not sure when I look at the error message.`Segmentation fault (core dumped)` means some program has crashed.

How about connecting to the remote server and test the Korean case instead of PyCharm remote run?

**Comment by znu808** [comment]
Hi DongJun,

First I had tried again in the server ( not Pycharm Remote run), the result was same with previous.
But, as your advise, I also thought encoding can be problem, so  I changed my encoding to "ko_KR.utf8" by "export LANG=ko_KR.utf8" command. And then tried it again. Finally it worked fine like below.
Thanks for your comment.

(claf) pycharm:/home02/pycharm_work/claf_test>**export LANG=ko_KR.utf8**
(claf) pycharm:/home02/pycharm_work/claf_test>
(claf) pycharm:/home02/pycharm_work/claf_test>python predict.py ./logs/squad_bert/checkpoint/model_22000.pkl --cuda_devices 0 --question "한글" --context "한글"
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
**Predict: {'text': '한글', 'score': 8.212509870529175}**
(claf) pycharm:/home02/pycharm_work/claf_test>
(claf) pycharm:/home02/pycharm_work/claf_test>
(claf) pycharm:/home02/pycharm_work/claf_test>
(claf) pycharm:/home02/pycharm_work/claf_test>python predict.py ./logs/squad_bert/checkpoint/model_22000.pkl --cuda_devices 0 --question "캐나다 초대수상인 존 맥도날드가 속해있는 정당은 무엇인가?" --context "초기 캐나다의 존재는 대륙횡단철도건설과 같은 대형사업에 의해 좌지우지되었다. 대륙횡단 철도건설은 캐나다 초대수상인 존 맥도날드(John A. Macdonald)의 보수당이 여러 이유 때문에 시작한 사업이었다. 브리티시 컬럼비아는 연방에 가입하는 조건을 동부지역과 이어지는 교통수단을 내걸었다. 결과 정부는 태평양과 동부의 여러 주를 잇는 철도를 1871년 7월 20일 이후 10년안에 건설할 것을 제안했다. 맥도날드 수상은 철도건설을 통일된 대륙국가를 건설하는 데에 필수적이라고 여겼다. 이에 더해서 퀘백 주와 온 타리오 주에 있는 공업업자들은 서부 캐나다의 자원을 얻고 싶었고, 또한 제조한 물품을 팔 수 있는 시장으로 여기기도 하였다."
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
**Predict: {'text': '보수당', 'score': 9.013720273971558}**

**Comment by DongjunLee** [comment]
That's great :)
Now that the problem has been resolved, I close the issue.
