### ISSUE TITLE
predict 이슈

### ISSUE THREAD

**Issue by Chad4545** [naver/claf#24]
roberta large 모델을 사용해서 train후 
predict.py 를 사용하는데 에러가 나네요.
 ValueError: '[SEP]' is not in list

**Comment by DongjunLee** [comment]
@Chad4545 

안녕하세요,

에러메시지의 디테일인 stack trace까지 공유를 해주실 수 있으신가요?
추가로 사용했던 커맨드도 부타드립니다.
어떤 Task 에 대해서 `predict.py`를 이용하신 것인지 알 수 있어야 도움을 드릴 수 있을 것으로 생각됩니다.

**Comment by Chad4545** [comment]
답변감사드립니다.

현재 squad dataset에 대하며  roberta_large모델 학습한 상황이고,
predict.py 사용한 상태입니다.


사실 궁극적인 목표는 korquad data 학습시킨 bert_cased모델에 대해서 predict을 하고 싶은데
1차적으로 squad - roberta 로 해보고있습니다.

2019년 10월 12일 (토) 오후 9:08, Dongjun Lee <notifications@github.com>님이 작성:

**Comment by DongjunLee** [comment]
RoBERTa는 최근에 추가된 상황이고, BERT 모델은 테스트코드까지 작성되어있는 상황이라 문제가 없으실 것으로 생각됩니다. :)

위에 ```ValueError: '[SEP]' is not in list``` 에러가 난 상황을 간단히 설명드리자면..
RoBERTa에서는 SEP_token 을 `</s>` 로 사용하고 있기 때문에 에러가 나는 것 입니다.

수정 예정입니다..!

**Comment by Chad4545** [comment]
감사합니다 해결했습니다.!!
좋은 라이브러리 공개해주셔서 다시 감사드립니다.!

2019년 10월 13일 (일) 오후 9:08, Dongjun Lee <notifications@github.com>님이 작성:

**Comment by DongjunLee** [comment]
네 감사합니다 :)
RoBERTa의 predict.py 오류가 남아있기는 하지만..
bert는 이슈가 없으므로 닫겠습니다.
