### ISSUE TITLE
fasttext.wiki.ko.300d.txt 파일 생성 방법

### ISSUE THREAD

**Issue by GMDennis** [naver/claf#25]
korQuAD BiDAF 를 돌리려는데, fasttext.wiki.ko.300d.txt 생성 방법을 못찾겠네요

가이드가  있으면 더 좋을 것 같습니다.!

**Comment by DongjunLee** [comment]
@GMDennis 

안녕하세요, 

fasttext 와 같은 Pretrained Vector는 [이곳](https://naver.github.io/claf/docs/_build/html/contents/pretrained_vector.html) 에 정리되어있습니다. :)

정확히는 [Word vectors for 157 languages trained on Wikipedia and Crawl.](https://github.com/facebookresearch/fastText/blob/master/docs/crawl-vectors.md) 이 페이지에서 Korean `text`를 받고, 압축을 풀여 연결해주시면 됩니다.

좋은 의견 감사합니다!

**Comment by GMDennis** [comment]
빠른 답변 감사합니다.! 다운 받고 압축 풀어도 같은 이름 파일이 없어서요, 

말씀하신 게 https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ko.300.vec.gz 이 파일 압축 풀고 파일명만 바꿔주면 된다는 얘기신거 같군요. :>

**Comment by DongjunLee** [comment]
아, 네네 맞습니다!
제가 너무나도 불친절하게 그냥 적어놓았군요 ㅠㅠ
파일명을 바꿔서 path 넣어주신다음 돌리면 됩니다.

**Comment by DongjunLee** [comment]
이 이슈는 해결하신 것으로 보아, 닫도록 하겠습니다.
