### ISSUE TITLE
flatten_parameters()

### ISSUE THREAD

**Issue by GMDennis** [naver/claf#26]
korquad bidaf 모델을 돌리니까 /pytorch/aten/src/ATen/native/cudnn/RNN.cpp:1236: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().

이런 warning 이 뜨는데 해결방법이 있을까요??

**Comment by DongjunLee** [comment]
안녕하세요,

저 warning을 해결하기 위해서 ```forward_rnn_with_pack``` 이 함수를 추가했었습니다.
음.. 사실 GPU 메모리만 더 사용하는 것 뿐이지 성능이나 다른 부분에 문제가 되지는 않습니다.

그래서 메모리에 문제가 있는 상황이 아니라면 그대로 놔두셔도 무방하다고 생각합니다.

**Comment by GMDennis** [comment]
@DongjunLee 네 돌려보니까 재현 잘되네요 ^^;; 감사합니다.
