### ISSUE TITLE
training이 오류가 납니다

### ISSUE THREAD

**Issue by onting** [naver/claf#28]
python train.py --basic_config korquad/drqa
python train.py --basic_config korquad/bidaf
위의 명령어로 학습시키려고 하는데 tokenizer error가 나면서 다음 오류를 내면서 꺼집니다.
![image](https://user-images.githubusercontent.com/10670129/68162382-3ecac280-ff9b-11e9-9589-3528cfd9036d.png)
mecab과 requirement는 설치했습니다. 도와주세요

**Comment by DongjunLee** [comment]
`<fasttext.wiki.ko.300d.txt>` 는 파일을 직접 받으셔서 열결해야한다는 것을 의미합니다.
#25 이 이슈를 참고해서 진행해주시길 바랍니다.

**Comment by onting** [comment]
Tokenizer error가 앞에 계속 발생하는거는 괜찮은건가요 warning이 엄청 많이 뜹니다.

**Comment by DongjunLee** [comment]
KorQuAD 를 돌리시는 것이라면, 정답 어절부분을 전처리하면서 생기는 '경고' 메시지입니다.
학습과 무관합니다.

**Comment by onting** [comment]
감사합니다. 이제 해결될 것 같네요. 집에가서 시도해보겠습니다.

**Comment by onting** [comment]
또 안되는 부분이 있네요. 다음과 같은 에러를 내며 꺼집니다. 명령어는 python3 train.py --basic_config korquad/docqa를 사용했습니다.
![image](https://user-images.githubusercontent.com/10670129/68995615-f385ad80-08d2-11ea-9868-c724dbe8c1e7.png)
혹시 tokenizer를 바꾸는 방법을 알려주실 수 있나요? 아무래도 word_tokenized_error가 신경쓰이네요.

**Comment by onting** [comment]
toeknizer를 바꿔봤는데 word_tokenized_error는 tokenizer랑 상관없네요. tokenizer랑 상관없이 다음으로 진행이 안되네요.

**Comment by onting** [comment]
혹시 WSL에서 돌린게 문제가 되는 걸까요?

**Comment by DongjunLee** [comment]
Tokenizer를 바꾸는 방법은 [문서](https://naver.github.io/claf/docs/_build/html/contents/tokens.html)를 참고해주세요.

word_tokenized_error 는 KorQuAD 데이터 전처리를 하면서 토큰이 제대로 나눠지지 않는 경우를 알려주는 것 입니다.
그리고 위에 에러로 올려주신 상황은 임베딩 파일의 인코딩이 맞지 않기 때문에 나는 에러입니다.

**Comment by onting** [comment]
cc.ko.300.vec파일의 인코딩을 확인해보니까 utf-8로 되어있던데 안되는 이유를 모르겠습니다. 도와주세요.

**Comment by onting** [comment]
아, 아무래도 cc.ko.300.vec파일이 이상한것 같네요. iconv로 utf-8에서 utf-8로 보내는 작업을 했는데 illegal sequance가 있다면서 종료되네요. 혹시 파일좀 공유해주실 수 있나요?

**Comment by onting** [comment]
cc.ko.300.vec에 문제가 있는건 확실해 보이네요. fasttext github에 이슈는 올렸습니다. 이 문제를 회피하기 위해서 word_embebbing.py 파일을 수정했는데 PR 보낼까요?

**Comment by DongjunLee** [comment]
네네, PR은 언제나 환영입니다.
다만 학습에서 에러가 없는지, 모델을 불러와서 평가할때 에러가 없을 시는 확인이 필요하겠네요.
제가 다른 파일을 가지고 있지는 않아서 공유를 드리기 어려울 것 같습니다.
