### ISSUE TITLE
Pre-trained model은 없나요

### ISSUE THREAD

**Issue by onting** [naver/claf#29]
Pre-trained 모델을 제공하면 training 시간을 줄일 수 있을것 같습니다.

**Comment by DongjunLee** [comment]
어떤 Pre-trained 모델을 말씀하시는 것인지 정확하게 파악은 안 됩니다만..
`BERT` 를 말씀하시는 것이라면 Google의 Multilingual 모델을 사용하시면 됩니다.

그 외에도 [KoBERT](https://github.com/SKTBrain/KoBERT) 도 공개되어 있어, 활용하실 수 있으실 것으로 생각됩니다.

**Comment by onting** [comment]
학습 없이 predict할 수 있는model은 없을까해서 어쭤봤습니다. 컴퓨터 사양이 좋지 않거든요. 제가 실행했을때는 checkpoint가 없다고 떴거든요.

**Comment by DongjunLee** [comment]
아아, 그런 부분들은 추후 [PyTorch Hub](https://pytorch.org/hub/) 를 이용하는 방향으로 가야합니다.
