### ISSUE TITLE
train.py가 gpu모드를 쓸 수 없습니다

### ISSUE THREAD

**Issue by onting** [naver/claf#33]
![image](https://user-images.githubusercontent.com/10670129/69820827-5ec16f00-1245-11ea-9bcf-ce55a4d45272.png)
gpu모드에서 동작하지 않는 문제가 있습니다. self.config에 cuda_devices가 존제하지 않는 문제인데 이게 nsml에서 돌리면 동작하지만 로컬에서 돌리는 코드에서 실수가 있는것 같습니다. 저도 해결 방법을 찾아보고 있겠습니다.

**Comment by onting** [comment]
해결 방법 찾았습니다. 
```
self.config.__setattr__("cuda_devices", [torch.device('cuda:0')])
```
이 코드를 experiment.py의 78줄에 추가하면 돌아갑니다.

**Comment by DongjunLee** [comment]
안녕하세요, 너무도 늦은 이슈 대응이네요 ㅠㅠ

아래와 같이 `base_config` 에 넣어주시면, GPU 모드로 사용이 가능합니다.

```java script
     ...
     "optimizer": {
         "learning_rate": 0.00003,
         "op_type": "adamw",
         "adamw": {
             "weight_decay": 0.01
         },
         "lr_scheduler_type": "warmup_linear",
         "warmup_linear": {
             "warmup_proportion": 0.1
         }
     },
     "seed_num": 42,
     "cuda_devices": [0]
 }
```

감사합니다.
