### ISSUE TITLE
하이퍼파라미터에 대한 질문입니다

### ISSUE THREAD

**Issue by ParkWanJae** [naver/claf#34]
https://github.com/naver/claf/blob/d5df036ea363f000dbdee6658be4a1b997866c0b/claf/data/reader/bert/squad.py#L321-L358

## max_seq_length

context_max_length는 아래의 소스와 같이 strided_context_length를 설정하는데 영향을 주어서
context를 자르는 범위를 정하는 것으로 확인했습니다.

```python

        context_stride_spans = []
        while start_offset < len(context_sub_tokens):
            strided_context_length = len(context_sub_tokens) - start_offset
            if strided_context_length > context_max_length:
                strided_context_length = context_max_length

            context_stride_spans.append((start_offset, strided_context_length))
            if start_offset + strided_context_length == len(context_sub_tokens):
                break
            start_offset += min(strided_context_length, self.context_stride)

```

그런데 context_max_length를 생성하는데 max_seq_length에 question_sub_tokens과 3을 빼고
생성되는데 만약 question_sub_tokens의 길이가 max_seq_length를 넘어가는 경우 무한루프에 빠지는 것으로 확인되었습니다. 어떻게 조치하면 좋을지 알려주시면 감사하겠습니다.

그리고 question_sub_tokens의 길이에 따라서 context_max_length가 동적으로 변하는데 만약 질문의 길이가
긴 경우 좀더 잘게 context를 자르고 질문의 길이가 짧은 경우 context를 크게 자르는 이유를 알고 싶습니다.

## max_question_length

bert_tokens 생성시 질문이 max_question_length의 범위를 넘어가는 경우 잘려서 들어갑니다.
이부분은 전처리시 질문의 길이를 맞추든지 아니면 max_question_length의 길이를 크게하면 되는지 
알고 싶습니다

```python

        features, labels = [], []
        for (start_offset, length) in context_stride_spans:
            bert_tokens = [Token(self.CLS_TOKEN)]
            bert_tokens += question_sub_tokens[: self.max_question_length]
            bert_tokens += [Token(self.SEP_TOKEN)]
            bert_tokens += context_sub_tokens[start_offset : start_offset + length]
            bert_tokens += [Token(self.SEP_TOKEN)]
            features.append(bert_tokens)


```

**Comment by DongjunLee** [comment]
안녕하세요,
우선은 BERT에 토큰이 어떻게 들어가는지 말씀드리면서, 이야기 드리면 좋을 것 같습니다.

```
[CLS] Questions Tokens ... [SEP] Passage Tokens [SEP]
```

이와 같은 형태로 Input이 들어가게 되고, 보통 모델 자체의 `max_seq_length` 은 512 입니다.

1. 이 길이를 넘어서는 `question_sub_tokens` 인풋을 받는 것은 불가능하기 때문에, 이 문제를 해결하고 싶다면 `max_seq_length` 가 더 긴 모델을 확보가 선행되어야 합니다.

2. `max_seq_length` 가 고정이기 때문에, `question_sub_tokens` 이 커지면 `context_max_length` 이 줄어듭니다.
