### ISSUE TITLE
Error occured in data reading by Bert_basic tokenizer

### ISSUE THREAD

**Issue by znu808** [naver/claf#4]
Hi,

As I konw, in case of lang code == "ko", tokenizer is hardcoded as a "mecab_ko" in squad_bert reader.
so I had changed the tokenizer to "bert_basic", and then tried to train again for "KorQuAD_v1.0_train.json" data. But, below error was occured.

I found the fact that t**he unicode “\u200e”, “\u00” in korQuad train dataset cause the error in data reading process when use "bert_basic" tokenizer.** So  I removed those unicodes in dataset and then tried again. As a result, it worked fine.

Could you let me know why this error occued?

**[Error result]**
train:  22%|███████▎                         | 312/1420 [00:34<02:35,  7.14it/s]Traceback (most recent call last):
  File "/home/pycharm/workspace/claf_test/train.py", line 15, in <module>
    experiment()
  File "/home02/pycharm_work/claf_test/claf/learn/experiment.py", line 122, in __call__
    train_loader, valid_loader, optimizer = self.set_train_mode()
  File "/home02/pycharm_work/claf_test/claf/learn/experiment.py", line 176, in set_train_mode
    datas, helpers = data_reader.read()
  File "/home02/pycharm_work/claf_test/claf/data/reader/base.py", line 55, in read
    batch, helper = self._read(file_path, data_type=data_type)
  File "/home02/pycharm_work/claf_test/claf/data/reader/bert/squad.py", line 97, in _read
    context_text, context_tokens
  File "/home02/pycharm_work/claf_test/claf/data/reader/bert/squad.py", line 297, **in _convert_to_spans
    f"\n{raw_text} \n\n{joined_tokenized_text} \nToken: {token}, Index: {temp}, Current Index: {curr_idx}"
ValueError:** 
이 영화 제작과는 별개로, 1990년대 중반에, 월트 디즈니 컴퍼니가 야마토의 영어 리메이크 버전인 스타 블레이저의 저작권을 사들였었는데 영화로 제작하지는 못했었다. TBS의 영화 제작을 담당하는 TBS 필름스는 2005년경부터 실사판을 계획하고 있었다. 2009년 7월 17일, 원래 '우주전함 야마토' 텔레비전 시리즈의 제작자이자 스태프인 이시구로 노보루‎는 그의 오타콘 패널에서 우주전함 야마토의 실사영화 버전을 개발 중임을 밝혔다. "꿈의 프로젝트"라 불리며 2010년 12월에 개봉 계획이고 22억 엔의 제작비인 이 프로젝트는, 《리터너》와 《올웨이즈 3번가의 석양》 시리즈로 잘 알려진 야마자키 다카시 감독이 맡기로 했다. 야마토는 개봉 전부터 어마어마한 제작비로 일본 영화계에 화두가 되었다. 

이 영화 제작과는 별개로 , 1990년대 중반에 , 월트 디즈니 컴퍼니가 야마토의 영어 리메이크 버전인 스타 블레이저의 저작권을 사들였었는데 영화로 제작하지는 못했었다 . TBS의 영화 제작을 담당하는 TBS 필름스는 2005년경부터 실사판을 계획하고 있었다 . 2009년 7월 17일 , 원래 ' 우주전함 야마토 ' 텔레비전 시리즈의 제작자이자 스태프인 이시구로 노보루는 그의 오타콘 패널에서 우주전함 야마토의 실사영화 버전을 개발 중임을 밝혔다 . " 꿈의 프로젝트 " 라 불리며 2010년 12월에 개봉 계획이고 22억 엔의 제작비인 이 프로젝트는 , 《 리터너 》 와 《 올웨이즈 3번가의 석양 》 시리즈로 잘 알려진 야마자키 다카시 감독이 맡기로 했다 . 야마토는 개봉 전부터 어마어마한 제작비로 일본 영화계에 화두가 되었다 . 
**Token: 노보루는, Index: -1, Current Index: 196**

**Comment by DongjunLee** [comment]
First of all, The reason I used `word_tokenizer (mecab_ko)` is because of the result of `word_tokenizer` affects the correct answer.

- With MeCab: answer 프로젝트
- Without MeCab: answer 프로젝트는

Next, `subword_tokenizer` includes `bert_basic`. [Here](https://naver.github.io/claf/docs/_build/html/contents/tokens.html) you can find more information.

So, you don't need to change and just use original one.

**Comment by znu808** [comment]
If I want to use other korean tokenizer such as Okt, Komoran...etc for comparing the performance, is there possible way to use it? ( I guess it need to modify the word.py )
Thanks.

**Comment by DongjunLee** [comment]
That's right :)

```python
def _mecab_ko(self, text):
    if self.word_tokenizer is None:
        from konlpy.tag import Mecab

        self.word_tokenizer = Mecab()
    return self.word_tokenizer.morphs(text)
```

It will be very helpful to implement it with code style like above and make it a pull request.

**Comment by znu808** [comment]
I got it, I will try as your advice.
Thanks a lot :)

**Comment by znu808** [comment]
Hi Dongjun,

One more question. For example, ["끌려"] is tokenized to ["끌리, "어" ] in ohter Tokenizer (Khaiii, Komoran...). So this caused the error in **_convert_to_spans** function.  (Actually line 297 in /bert/squad.py). I think that caused because tokenized word can't be found in context text.

Could you advise how to solve this problem?

Traceback (most recent call last):
  File "/home/pycharm/workspace/claf_test/train.py", line 15, in <module>
    experiment()
  File "/home02/pycharm_work/claf_test/claf/learn/experiment.py", line 122, in __call__
    train_loader, valid_loader, optimizer = self.set_train_mode()
  File "/home02/pycharm_work/claf_test/claf/learn/experiment.py", line 176, in set_train_mode
    datas, helpers = data_reader.read()
  File "/home02/pycharm_work/claf_test/claf/data/reader/base.py", line 55, in read
    batch, helper = self._read(file_path, data_type=data_type)
  File "/home02/pycharm_work/claf_test/claf/data/reader/bert/squad.py", line 97, in _read
    context_text, context_tokens
  File "/home02/pycharm_work/claf_test/claf/data/reader/bert/squad.py", line 297, in _convert_to_spans
    **f"\n{raw_text} \n\n{joined_tokenized_text} \nToken: {token}, Index: {temp}, Current Index: {curr_idx}"**

ValueError: 
1839년 바그너는 괴테의 파우스트을 처음 읽고 그 내용에 마음이 끌려 이를 소재로 해서 하나의 교향곡을 쓰려는 뜻을 갖는다. 이 시기 바그너는 1838년에 빛 독촉으로 산전수전을 다 걲은 상황이라 좌절과 실망에 가득했으며 메피스토펠레스를 만나는 파우스트의 심경에 공감했다고 한다. 또한 파리에서 아브네크의 지휘로 파리 음악원 관현악단이 연주하는 베토벤의 교향곡 9번을 듣고 깊은 감명을 받았는데, 이것이 이듬해 1월에 파우스트의 서곡으로 쓰여진 이 작품에 조금이라도 영향을 끼쳤으리라는 것은 의심할 여지가 없다. 여기의 라단조 조성의 경우에도 그의 전기에 적혀 있는 것처럼 단순한 정신적 피로나 실의가 반영된 것이 아니라 베토벤의 합창교향곡 조성의 영향을 받은 것을 볼 수 있다. 그렇게 교향곡 작곡을 1839년부터 40년에 걸쳐 파리에서 착수했으나 1악장을 쓴 뒤에 중단했다. 또한 작품의 완성과 동시에 그는 이 서곡(1악장)을 파리 음악원의 연주회에서 연주할 파트보까지 준비하였으나, 실제로는 이루어지지는 않았다. 결국 초연은 4년 반이 지난 후에 드레스덴에서 연주되었고 재연도 이루어졌지만, 이후에 그대로 방치되고 말았다. 그 사이에 그는 리엔치와 방황하는 네덜란드인을 완성하고 탄호이저에도 착수하는 등 분주한 시간을 보냈는데, 그런 바쁜 생활이 이 곡을 잊게 한 것이 아닌가 하는 의견도 있다. 

1839 년 바그너 는 괴테 의 파우스트 을 처음 읽 고 그 내용 에 마음 이 끌리 어 이 를 소재 로 하 여서 하나 의 교향곡 을 쓰 려는 뜻 을 갖 는다 . 이 시기 바그너 는 1838 년 에 빛 독촉 으로 산전수전 을 다 걲 은 상황 이 라 좌절 과 실망 에 가득 하 였 으며 메피스토펠레스 를 만나 는 파우스트 의 심경 에 공감 하 였 다고 하 ㄴ다 . 또한 파리 에서 아 브 네크 의 지휘 로 파리 음악원 관현악단 이 연주 하 는 베토벤 의 교향곡 9 번 을 듣 고 깊 은 감명 을 받 았 는데 , 이것 이 이듬해 1 월 에 파우스트 의 서곡 으로 쓰이 어 지 ㄴ 이 작품 에 조금 이 라도 영향 을 끼치 었 으리라는 것 은 의심 하 ㄹ 여지 가 없 다 . 여기 의 라단조 조성 의 경우 에 도 그 의 전기 에 적히 어 있 는 것 처럼 단순 하 ㄴ 정신 적 피로 나 실의 가 반영 되 ㄴ 것 이 아니 라 베토벤 의 합창 교향곡 조성 의 영향 을 받 은 것 을 보 ㄹ 수 있 다 . 그렇 게 교향곡 작곡 을 1839 년 부터 40 년 에 걸치 어 파리 에서 착수 하 였 으나 1 악장 을 쓰 ㄴ 뒤 에 중단 하 였 다 . 또한 작품 의 완성 과 동시 에 그 는 이 서곡 ( 1 악장 ) 을 파리 음악원 의 연주회 에서 연주 하 ㄹ 파트보 까지 준비 하 였 으나 , 실제로 는 이루어지 지 는 않 았 다 . 결국 초연 은 4 년 반 이 지나 ㄴ 후 에 드레스덴 에서 연주 되 었 고 재연 도 이루어지 었 지만 , 이후 에 그대로 방치 되 고 말 았 다 . 그 사이 에 그 는 리 엔치 와 방황 하 는 네덜란드 인 을 완성 하 고 탄호이 저 에 도 착수 하 는 등 분주 하 ㄴ 시간 을 보내 었 는데 , 그런 바쁘 ㄴ 생활 이 이 곡 을 잊 게 하 ㄴ 것 이 아니 ㄴ가 하 는 의견 도 있 다 . 
Token: 끌리, Index: -1, Current Index: 36

**Comment by DongjunLee** [comment]
Hi @znu808,

When I designed `Tokenizer`, it is assumed that there is no change in output of text.
That's why i do not implement `Khaiii` Tokenizer.

In this situation, it is appropriate to ensure that the results of Tokenizer are not transformed.

**Comment by znu808** [comment]
Hi Dongjun,

I see, that's why you use the Mecab. 
Thanks for your advice.
