### ISSUE TITLE
error!

### ISSUE THREAD

**Issue by directv00** [naver/claf#6]
I download docker image, trained and ran it.
Only got an error!.
Could you figure out what went wrong?

Read Wiki Articles: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 21427/21427 [02:16<00:00, 157.48it/s]

Completed!

Traceback (most recent call last):

  File "machine.py", line 18, in <module>

    claf_machine = registry.get(f"machine:{machine_name}")(config)

  File "/workspace/claf/claf/machine/open_qa.py", line 34, in __init__

    self.load()

  File "/workspace/claf/claf/machine/open_qa.py", line 55, in load

    self.rc_experiment = self.make_module(reasoning_config.reading_comprehension)

  File "/workspace/claf/claf/machine/base.py", line 64, in make_module

    experiment = Experiment(Mode.PREDICT, experiment_config)

  File "/workspace/claf/claf/learn/experiment.py", line 48, in __init__

    self.load_setting()

  File "/workspace/claf/claf/learn/experiment.py", line 89, in load_setting

    cuda_devices, checkpoint_path, prev_cuda_device_id=prev_cuda_device_id

  File "/workspace/claf/claf/learn/experiment.py", line 101, in _read_checkpoint

    f"cuda:{prev_cuda_device_id}": f"cuda:{cuda_devices[0]}"

TypeError: 'NoneType' object is not subscriptable

**Comment by soheeyang** [comment]
To run claf_machine on a computer where cuda is available, please specify `cuda_devices` in the machine config file where an `experiment` type module configuration is defined(seems like you are using `open_qa` so this would be the `reading_comprehension` module), like:

![image](https://user-images.githubusercontent.com/28291528/55205745-64c70200-5217-11e9-9d97-7c94855c68e0.png)

**Comment by directv00** [comment]
Thanks, it finally works. But it gives other kind of errors. It seemed trade-off between memory overflow and max_sequence_size. The default max_sequence_size sets 2,000. But the bigger the size, the more probable it gives memory overflow. The smaller the size, the more probable it gives size coverage problem. It is not easy to find an optimum value between them. What should I do?

**Comment by soheeyang** [comment]
I'm afraid there is no silver bullet for the tradeoff issue... 😥 The choice of max_sequence_size depends on the GPU (memory of the GPU) that you use. I think the best way to find the optimum value is by trial and error.

**Comment by directv00** [comment]
OK, it's no problem to set max_sequence_size smaller one. But how do I avoid doc. with more than max_sequence_size when choosing docs?

**Comment by DongjunLee** [comment]
I think that when the document is long, splitting the document into paragraphs with smaller than `max_sequence_size` will produce better results.
