### ISSUE TITLE
How to get the many answers in predict mode?

### ISSUE THREAD

**Issue by znu808** [naver/claf#8]
Hi,

As I know, in predict mode, there is only one best answer as a result. (bert for qa model)
But If i want to get the 10 best answers(order by score) in predict mode, how to get them?

Is there any parameter like "n_best_size" (exist in BERT google version) ?
It will be appreciated, if you give advice for modify the source code.

Thanks.

**Comment by DongjunLee** [comment]
HI @znu808, Sorry for late comment.

The below code looks like work with `start_logits` and `end_logits`.

```python
def _get_best_indexes(logits, n_best_size):
    """Get the n-best logits from a list."""
    index_and_score = sorted(enumerate(logits), key=lambda x: x[1], reverse=True)

    best_indexes = []
    for i in range(len(index_and_score)):
        if i >= n_best_size:
            break
        best_indexes.append(index_and_score[i][0])
    return best_indexes

...

start_indexes = _get_best_indexes(result.start_logits, n_best_size)
end_indexes = _get_best_indexes(result.end_logits, n_best_size)

for start_index in start_indexes:
    for end_index in end_indexes:
        # We could hypothetically create invalid predictions, e.g., predict
        # that the start of the span is in the question. We throw out all
        # invalid predictions.
        if start_index >= len(bert_token):
            continue
        if end_index >= len(bert_token):
            continue
        if bert_token[start_index] is None:
            continue
        if bert_token[end_index] is None:
            continue
        if end_index < start_index:
            continue
        length = end_index - start_index + 1
        if length > max_answer_length:
            continue
        prelim_predictions.append(
            _PrelimPrediction(
                feature_index=feature_index,
                start_index=start_index,
                end_index=end_index,
                start_logit=result.start_logits[start_index],
                end_logit=result.end_logits[end_index]))
```

**Comment by znu808** [comment]
Thanks @DongjunLee ,

I have solved the problem with your advice.
And I have another simple question.

Is Answer's Score is a absolute basis of prediction regardless of where it from?
For example, If context is divided to 3 collections of BERT TOKENS by max_seq_length.
and if second ordered answer's score of 1st BERT TOKENS collection is higher than first ordered answer of 2nd BERT TOKENS collection, could I trust second ordered answer of 1st BERT TOKENS collection is better?

**Comment by DongjunLee** [comment]
You're welcome :)

It's right that you understand.
I'm not sure but, It is shown to be reliable because the model learns with a large number of examples which split by `doc_stride`.

**Comment by znu808** [comment]
I got it ! Thanks to confirm. I will close this issue. :)
